data:
  class_path: autoencoder.datasets.MRIDataModule
  init_args:
    data_file: ./data/data_mudi.hdf5
    batch_size: 256
    subject_list_train:
      - 11
      - 12
      - 13
      - 14
    subject_list_val:
      - 15
    in_memory: true
    num_workers: 0
