trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        patience: 5
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
model:
  class_path: autoencoder.models.FCNDecoder
  init_args:
    input_size: 60
    output_size: 288
    hidden_layers: 2
    learning_rate: 0.001
data:
  class_path: autoencoder.datasets.MRIDataModule
  init_args:
    include_parameters: data/HCP-60-random-equal-b.txt
    return_target: True
tags:
  data: HCP
  input_size: "60"
