trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
model:
  class_path: autoencoder.models.SphericalDecoder
  init_args:
    n_ti: 1
    n_te: 1
    linear_layer_input_size: 1920
    n_shells:
      - 5
      - 8
      - 16
    L:
      - 2
      - 2
      - 0
    learning_rate: 0.001
data:
  class_path: autoencoder.datasets.MRIDataModule
  init_args:
    include_features: ./data/latent_features.txt
    spherical_transform:
      class_path: autoencoder.datasets.SphericalTransformer
      init_args:
        l_max: 2
        symmetric: true
        inversion_n_iters: 1000
