trainer:
  callbacks:
    # - class_path: pytorch_lightning.callbacks.EarlyStopping
    #   init_args:
    #     monitor: "val_loss"
    #     patience: 5
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
model:
  class_path: autoencoder.models.SphericalDecoder
  init_args:
    learning_rate: 0.0001
data:
  class_path: autoencoder.datasets.MRIDataModule
  init_args:
    include_parameters: data/HCP-60-random-b1000-b2000.txt
    return_target: True
    transform:
      class_path: autoencoder.datasets.SphericalTransformer
      init_args:
        l_max: 6
        symmetric: true
        inversion_n_iters: 1000
tags:
  data: HCP
  input_size: "60"
