data:
  class_path: autoencoder.datasets.MRIDataModule
  init_args:
    parameters_file_path: ./data/prj_HCP_parameters.hdf5
    data_file_path: ./data/prj_HCP_data.hdf5
    train_subject_ids:
      - 933253
      - 196952
      - 127731
      - 559457
    validate_subject_ids:
      - 103010
      - 146836
    batch_size: 256
    num_workers: 0
