data:
  class_path: autoencoder.datasets.MRIDataModule
  init_args:
    data_file: ./data/data_hcp.hdf5
    batch_size: 256
    subject_list_train:
      - tbd
    subject_list_val:
      - tbd
    in_memory: true
    num_workers: 0
    exclude: "./data/hcp_exclude_b0.txt"
