trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
model:
  class_path: autoencoder.models.DelimitDecoder
  init_args:
    linear_layer_input_size: 2688
    linear_layer_output_size: 1344
    gradients_file_path: ./data/prj_MUDI_parameters.hdf5
    n_shells:
      - 4
      - 8
      - 16
    L:
      - 2
      - 2
      - 0
    learning_rate: 0.001
data:
  class_path: autoencoder.datasets.MRIDataModule
  init_args:
    include_parameters: ./data/mudi_include_latent.txt
    return_target: True
    transform:
      class_path: autoencoder.datasets.DelimitTransformer
