trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
model:
  class_path: autoencoder.models.SphericalDecoder
  init_args:
    parameters_file_path: ./data/prj_MUDI_parameters.hdf5
    sh_degree: 2
    n_shells: 3
    learning_rate: 0.0001
data:
  class_path: autoencoder.datasets.MRIDataModule
  init_args:
    include_parameters: ./data/MUDI-500-b8aaa2201b2a4e5895127541f5dd1122.txt
    return_target: True
    use_spherical_data: true
tags:
  data: MUDI
  input_size: "60"
