data:
  class_path: autoencoder.datasets.MRIDataModule
  init_args:
    parameters_file_path: ./data/prj_MUDI_parameters.hdf5
    data_file_paths:
      - ./data/prj_MUDI_subj_cdmri0011_data.hdf5
      - ./data/prj_MUDI_subj_cdmri0012_data.hdf5
      - ./data/prj_MUDI_subj_cdmri0013_data.hdf5
      - ./data/prj_MUDI_subj_cdmri0014_data.hdf5
      - ./data/prj_MUDI_subj_cdmri0015_data.hdf5
    batch_size: 256
    num_workers: 0
