data:
  class_path: autoencoder.datasets.MRIDataModule
  init_args:
    parameters_file_path: ./data/prj_MUDI_parameters.hdf5
    data_file_path: ./data/prj_MUDI_data.hdf5
    train_subject_ids:
      - 11
      - 12
      - 13
      - 14
    validate_subject_ids:
      - 15
    batch_size: 256
    num_workers: 2
