trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
model:
  class_path: autoencoder.models.SphericalDecoder
  init_args:
    n_ti: 28
    n_te: 3
    linear_layer_input_size: 2688
    linear_layer_output_size: 1344
    n_shells:
      - 4
      - 8
      - 16
    L:
      - 2
      - 2
      - 0
    learning_rate: 0.001
data:
  class_path: autoencoder.datasets.MRIDataModule
  init_args:
    include_parameters: ./data/mudi_include_latent.txt
    return_target: True
    transform:
      class_path: autoencoder.datasets.SphericalTransformer
      init_args:
        l_max: 2
        symmetric: true
        inversion_n_iters: 1000
